
import Navbar from "@/Component/Navbar";
import "./globals.css";



export const metadata = {
  title: "Family's Clothes House",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <head>
        <script src="https://kit.fontawesome.com/0b7094b591.js" crossorigin="anonymous"></script>
      </head>
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
