import Navbar from "@/Component/Navbar";
import "./globals.css";
import Script from "next/script";
import { MainProvider } from "@/context/MainContext";
import Footer from "@/Component/Footer";


export const metadata = {
  title: "Family's Clothes House",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <head>
        <Script
          src="https://kit.fontawesome.com/0b7094b591.js"
          crossOrigin="anonymous"
          strategy="afterInteractive"
        />
      </head>
      <body suppressHydrationWarning={true}>
        <MainProvider>
          <Navbar />
          {children}
          <Footer></Footer>
        </MainProvider>
      </body>
    </html>
  );
}
